### ISSUE TITLE
TabBar doesn't show normally.

### ISSUE THREAD

**Issue by sunnysab** [jimyag/star-microapp#1]
Hello! I'm using iPhone 12 (iOS 15.3.1, Wechat 8.0.18). However, the mini app doesn't show normally.

The screenshot is following:

![1646995022312](https://user-images.githubusercontent.com/11255727/157851415-d2d9750b-60ce-4192-809d-d598c4d4c73f.jpg)

Hoping repair as quickly as possible.

**Comment by zhangzqs** [comment]
Oh give it up, I think. Maybe the project had came to nothing
